version: '3'

services:
  bot:
    build: .
    container_name: gotc-rally-bot
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules 