[languages]
language = "nodejs"

[hosting]
route = "/"
directory = "/"

[env]
DISCORD_PUBLIC_KEY = "$DISCORD_PUBLIC_KEY"
DISCORD_TOKEN = "$DISCORD_TOKEN"
DISCORD_APPLICATION_ID = "$DISCORD_APPLICATION_ID"

[nix]
enabled = true

[unitTest]
language = "nodejs"

# Run command
run = "npm run start:replit" 